name: Bump version

on:
  workflow_dispatch:
    inputs:
      bump-type:
        description: "Bump Type"
        required: true
        default: "pre_l"
        type: choice
        options:
          - major
          - minor
          - patch
          - pre_l
      create-tag:
        description: "Create Tag"
        required: true
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Bump Version
        id: bump
        uses: callowayproject/bump-my-version@master
        env:
          BUMPVERSION_TAG: "${{ inputs.create-tag }}"
          BUMPVERSION_COMMIT: "true"
        with:
          args: ${{ inputs.bump-type }}
          github-token: ${{ secrets.GH_TOKEN }}

      - name: Check
        if: steps.bump.outputs.bumped == 'true'
        run: |
          echo "Version was bumped from ${{ steps.bump.outputs.previous-version }} to ${{ steps.bump.outputs.current-version }}!"
